<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'MyCLabs\\Enum\\' => array($vendorDir . '/myclabs/php-enum/src'),
    'Intraxia\\Jaxion\\' => array($vendorDir . '/intraxia/jaxion/src'),
    'Intraxia\\Gistpen\\' => array($baseDir . '/app'),
);
